services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Основной AMQP порт
      - "15672:15672" # Web UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  spring-app:
    build:
      context: ./API_gateway
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy

  cpp-server:
    build:
      context: ./cpp_GSL_server
    container_name: cpp-solver
    depends_on:
      rabbitmq:
        condition: service_healthy

  julia-server:
    build:
      context: ./Julia_server
    container_name: julia-solver
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: "amqp://guest:guest@rabbitmq:5672"
