services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672" # Основной AMQP порт
      - "15672:15672" # Web UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USERNAME}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"

  spring-app:
    build:
      context: ./API_gateway
    container_name: spring-app
    ports:
      - "${SPRING_PORT}:8080"
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy

  cpp-server:
    build:
      context: ./cpp_GSL_server
    container_name: cpp-solver
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  julia-server:
    build:
      context: ./Julia_server
    container_name: julia-solver
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    # environment:
    #   RABBITMQ_HOST: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}"
