global:
  scrape_interval: 10s  # 🔹 Запрашивать метрики каждые 5 секунд

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-app:8080']  # 🔹 Подключаем Spring Boot

# ✅ Мониторинг RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

  # ✅ Мониторинг C++ сервера через cAdvisor
  - job_name: 'cpp-solver'
    static_configs:
      - targets: ['cadvisor:8080']

  # ✅ Мониторинг Julia сервера через cAdvisor
  - job_name: 'julia-solver'
    static_configs:
      - targets: ['cadvisor:8080']

rule_files:
  - /etc/prometheus/prometheus-alerts.yml
